test commit

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -49,5 +49,6 @@ jobs:
         run: |
           terraform apply -auto-approve
       - name: destroy
-        run: |
-          terraform destroy -auto-approve
+        if: always()
+        run: | 
+          terraform destroy -auto-approve || echo "Destroy failed but continuing"
